"""
Catálogo de productos de la tienda, definido directamente en código.

Para agregar, editar o quitar un producto: edita la lista PRODUCTOS de abajo
y vuelve a correr la app (python run.py / flask run). La sincronización
crea lo que falte y actualiza precio/stock/descripcion/imagen de lo que cambió;
no borra productos que quites de esta lista (para eso usar el panel de admin).
"""

PRODUCTOS = [
    {
        'categoria': 'Accesorios',
        'nombre': 'Bolso Great Britain Accesories',
        'descripcion': 'Bolso elegante y espacioso, perfecto para tus accesorios diarios con un toque de estilo sofisticado.',
        'precio': 80,
        'stock': 79,
        'imagen': 'Bolso_Great_Britain_Accesories_80.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Bolso Pink Accesories',
        'descripcion': 'Bolso elegante y espacioso, perfecto para tus accesorios diarios con un toque de estilo sofisticado.',
        'precio': 60,
        'stock': 31,
        'imagen': 'Bolso_Pink_Accesories_60.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Bolso Style Aquarium Accesories',
        'descripcion': 'Bolso estilo aquario, perfecto para tus accesorios diarios con un toque de estilo único.',
        'precio': 90,
        'stock': 11,
        'imagen': 'Bolso_Style_Aquarium_Accesories_90.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Bufanda Black And Gold Accesories',
        'descripcion': 'Bufanda suave, ideal como un accesorio chic para tu outfit.',
        'precio': 60,
        'stock': 83,
        'imagen': 'Bufanda_Black_And_Gold_Accesories_60.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Bufanda Blue And Purple Bright Accesories',
        'descripcion': 'Bufanda suave, ideal  como un accesorio chic para tu outfit.',
        'precio': 55,
        'stock': 58,
        'imagen': 'Bufanda_Blue_And_Purple_Bright_Accesories_55.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Cinturón Desert Style Accesories',
        'descripcion': 'Cinturón de alta calidad con hebilla resistente, ideal para ajustar y estilizar tus prendas favoritas.',
        'precio': 30,
        'stock': 19,
        'imagen': 'Cinturón_Desert_Style_Accesories_30.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Cinturón Style Atado Brown Accesories',
        'descripcion': 'Cinturón de alta calidad con hebilla resistente, ideal para ajustar y estilizar tus prendas favoritas.',
        'precio': 40,
        'stock': 21,
        'imagen': 'Cinturón_Style_Atado_Brown_Accesories_40.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Gorra Cyber Pink Accesories',
        'descripcion': 'Gorra ajustable con diseño moderno, ideal para un look urbano y protección solar.',
        'precio': 50,
        'stock': 71,
        'imagen': 'Gorra_Cyber_Pink_Accesories_50.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Gorra Heart Black Accesories',
        'descripcion': 'Gorra ajustable con diseño moderno, ideal para un look urbano y protección solar.',
        'precio': 50,
        'stock': 24,
        'imagen': 'Gorra_Heart_Black_Accesories_50.webp',
    },
    {
        'categoria': 'Accesorios',
        'nombre': 'Mochila Bunny Brown Accesories',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño único y a la moda.',
        'precio': 50,
        'stock': 79,
        'imagen': 'Mochila_Bunny_Brown_Accesories_50.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Baggy Jean Bottom',
        'descripcion': 'Prenda inferior Baggy Jean, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 100,
        'stock': 76,
        'imagen': 'Baggy_Jean_Bottom_100.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Black Mini Skirt Bottom',
        'descripcion': 'Prenda inferior corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 32,
        'stock': 47,
        'imagen': 'Black_Mini_Skirt_Bottom_32.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Black Skirt Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 25,
        'stock': 33,
        'imagen': 'Black_Skirt_Bottom_25.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Cargo Jeans Flowers Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 50,
        'stock': 35,
        'imagen': 'Cargo_Jeans_Flowers_Bottom_50.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Cargo Pants Wide Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 90,
        'stock': 47,
        'imagen': 'Cargo_Pants_Wide_Bottom_90.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Mirage Magic Pant Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 49,
        'stock': 59,
        'imagen': 'Mirage_Magic_Pant_Bottom_49.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Panther Pant Black Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 55,
        'stock': 58,
        'imagen': 'Panther_Pant_Black_Bottom_55.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Pants Bell VCut Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 49,
        'stock': 27,
        'imagen': 'Pants_Bell_VCut_Bottom_49.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Plaid Mini Skirt Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 20,
        'stock': 47,
        'imagen': 'Plaid_Mini_Skirt_Bottom_20.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Siren Midi Skirt Black Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 69,
        'stock': 80,
        'imagen': 'Siren_Midi_Skirt_Black_Bottom_69.webp',
    },
    {
        'categoria': 'Bottoms',
        'nombre': 'Star Pants Black Bottom',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 59,
        'stock': 47,
        'imagen': 'Star_Pants_Black_Bottom_59.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Alicia Top Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 56,
        'imagen': 'Alicia_Top_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Beatriz Top Blue Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 27,
        'imagen': 'Beatriz_Top_Blue_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Beatriz Top Coral Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 47,
        'imagen': 'Beatriz_Top_Coral_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Beatriz Top Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 29,
        'stock': 76,
        'imagen': 'Beatriz_Top_Shirt_29.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Celia Sequin Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 33,
        'imagen': 'Celia_Sequin_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Gina Top Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 49,
        'stock': 23,
        'imagen': 'Gina_Top_Shirt_49.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Leah Shoulder Black Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 58,
        'imagen': 'Leah_Shoulder_Black_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Leah Shoulder Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 15,
        'imagen': 'Leah_Shoulder_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Panther Black Shirt',
        'descripcion': 'Top de diseño único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 45,
        'stock': 15,
        'imagen': 'Panther_Black_Shirt_45.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Rosalina Ruffle Top Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 20,
        'stock': 58,
        'imagen': 'Rosalina_Ruffle_Top_Shirt_20.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Silvia Top Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 39,
        'stock': 56,
        'imagen': 'Silvia_Top_Shirt_39.webp',
    },
    {
        'categoria': 'Tops',
        'nombre': 'Siren Vest Shirt',
        'descripcion': 'Top de diseño contemporáneo, fresco y versátil, excelente para combinar con tus prendas preferidas.',
        'precio': 69,
        'stock': 56,
        'imagen': 'Siren_Vest_Shirt_69.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Analog Maxi Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 79,
        'stock': 76,
        'imagen': 'Analog_Maxi_Dress_79.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Aurora Midi Pink Dress 35',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 40,
        'stock': 58,
        'imagen': 'Aurora_Midi_Pink_Dress_35_40.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Compression Ruched Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 59,
        'stock': 59,
        'imagen': 'Compression_Ruched_Dress_59.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Dreamland Dancer Pink Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 59,
        'stock': 71,
        'imagen': 'Dreamland_Dancer_Pink_Dress_59.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Flame Panther Dress',
        'descripcion': 'Prenda inferior con un estilo único, corte moderno que asegura comodidad y estilo todo el día.',
        'precio': 65,
        'stock': 15,
        'imagen': 'Flame_Panther_Dress_65.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Fringe Resort Mini Dress 35',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 40,
        'stock': 71,
        'imagen': 'Fringe_Resort_Mini_Dress_35_40.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Grommet Midi Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 59,
        'stock': 33,
        'imagen': 'Grommet_Midi_Dress_59.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Like Cherry Pie Mini Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 49,
        'stock': 35,
        'imagen': 'Like_Cherry_Pie_Mini_Dress_49.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Little Secret Mini Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 69,
        'stock': 59,
        'imagen': 'Little_Secret_Mini_Dress_69.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Odette Waist Mini Dress 35',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 40,
        'stock': 35,
        'imagen': 'Odette_Waist_Mini_Dress_35_40.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Pink Leopard Tank Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 69,
        'stock': 47,
        'imagen': 'Pink_Leopard_Tank_Dress_69.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Rebel Mon Blue Maxi Dress Aqua',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 70,
        'stock': 79,
        'imagen': 'Rebel_Mon_Blue_Maxi_Dress_Aqua_70.webp',
    },
    {
        'categoria': 'Vestidos',
        'nombre': 'Siren Hooded Maxi Dress',
        'descripcion': 'Vestido elegante de silueta impecable, perfecto para ocasiones especiales o un look casual sofisticado.',
        'precio': 69,
        'stock': 47,
        'imagen': 'Siren_Hooded_Maxi_Dress_69.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Blue Saldals Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 70,
        'stock': 33,
        'imagen': 'Blue_Saldals_Shoes_70.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Boots Combat Shoes',
        'descripcion': 'Calzado ergonómico y a la vanguardia de la moda, máxima comodidad en cada paso.',
        'precio': 110,
        'stock': 33,
        'imagen': 'Boots_Combat_Shoes_110.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Boots Cowgirl Pink Shoes',
        'descripcion': 'Calzado ergonómico y a la vanguardia de la moda, máxima comodidad en cada paso.',
        'precio': 140,
        'stock': 59,
        'imagen': 'Boots_Cowgirl_Pink_Shoes_140.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Boots Platform Long Shoes',
        'descripcion': 'Calzado ergonómico y a la vanguardia de la moda, máxima comodidad en cada paso.',
        'precio': 150,
        'stock': 58,
        'imagen': 'Boots_Platform_Long_Shoes_150.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Boots Platform Long White Shoes',
        'descripcion': 'Calzado ergonómico y a la vanguardia de la moda, máxima comodidad en cada paso.',
        'precio': 150,
        'stock': 11,
        'imagen': 'Boots_Platform_Long_White_Shoes_150.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Bullet High Heel Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 60,
        'stock': 27,
        'imagen': 'Bullet_High_Heel_Shoes_60.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Delight High Heels Red Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 130,
        'stock': 24,
        'imagen': 'Delight_High_Heels_Red_Shoes_130.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'High Heels Ballet Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 50,
        'stock': 47,
        'imagen': 'High_Heels_Ballet_Shoes_50.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Platforms High Heels Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 140,
        'stock': 35,
        'imagen': 'Platforms_High_Heels_Shoes_140.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Saldals Charms Pink Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 105,
        'stock': 58,
        'imagen': 'Saldals_Charms_Pink_Shoes_105.webp',
    },
    {
        'categoria': 'Zapatos',
        'nombre': 'Sandals Black Shoes',
        'descripcion': 'Prenda exclusiva de la colección, ideal para complementar tu estilo único. Diseño cómodo y a la moda.',
        'precio': 80,
        'stock': 15,
        'imagen': 'Sandals_Black_Shoes_80.webp',
    },
]
